from typing import Protocol


class DistroProtocol(Protocol):
  def prepare_base_system(self) -> list[str]: ...

  def install_base_system(self, packages: list[str], repository: str | None = None) -> str: ...

  def install_packages(self, packages: list[str], repository: str | None = None) -> str: ...

  def reconfigure_system(self) -> str: ...

  def reconfigure_locale(self) -> str: ...

  def enable_services(self, services: list[str]) -> str: ...

  def locale_settings(self, locale: str, libc: str | None = None) -> list[tuple[str, list[str]]]: ...

  def timezone_settings(self, keymap: str, timezone: str | None = None) -> list[tuple[str, list[str]]]: ...

  def initramfs_config(self, crypt_uuid: str, luks_pass: str) -> str: ...

  def base_packages(self) -> list[str]: ...

  def default_services(self) -> list[str]: ...
